on:
  push:
    branches: [ feature/publish-test ]

install:
  FILE="-Dfile=app/libs/AuthMeSDK-1.1.1.aar"
  mvn install:install-file $FILE -DgroupId=com.authme -DartifactId=authme.sdk -Dversion=1.1.0 -Dpackaging=aar